### ISSUE TITLE
Offer alternative to memcache outside docker

### ISSUE THREAD

**Issue by Xuzzo** [aai-institute/pyDVL#124]
Our data shapley methods heavily rely on memcache. On windows, the best (only?) way to use memcache is through Docker, which is a problem cause Docker is not free of charge. 
In the spirit of making our repository plug and play and as independent as possible, we should offer an alternative to memcache within our utility wrapper.

**Comment by mdbenito** [comment]
Disabling memcache by default would be a stopgap, see #210 => moving this to a later milestone
