### ISSUE TITLE
Automated checks for PRs

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#131]
In order to enforce a certain set of guidelines and requirements on the project we need to first find the right tool to run those checks automatically and then decide on the checks that should be run against all PRs.

- [ ] Find tool to run automated checks against PRs
- [ ] Agree on a set of checks that each PR should fulfill

For the tool, I think we should use [Danger](https://github.com/danger/danger-js) a tool used internally by Gitlab and by our MLOps team and that was recently presented in a developer bi-weekly.

It requires creating a `dangerfile`, a configuration file in the root of the repository and then using the provided actions in CI to run the checks. It will post comments on the PR with the results of the checks.

An example `dangerfile` looks like this:

```javascript
import { danger } from "danger"

const docs = danger.git.fileMatch("docs/**/*.rst")
const code = danger.git.fileMatch("src/**/*.py")
const tests = danger.git.fileMatch("tests/**/*.py")

if (docs.edited) {
  message("Thanks for writing documentation")
}

if (code.modified && !tests.modified) {
  warn("You have code changes without tests.")
}

```

**Comment by schroedk** [comment]
Not needed by now, reopen, if number of contributions goes up. Will close.
