### ISSUE TITLE
Add contributing documentation for when a module/feature was added/modified/deprecated

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#167]
We should add to the contributing documentation the use of ~the [.. versionadded::](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionadded), [.. versionchanged::](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-versionchanged), [.. deprecated::](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) sphinx directives~ mkdocs admonitions in docstrings to document when features are added/changed/deprecated for developers and for end users.

**Comment by mdbenito** [comment]
Document curent practice with @deprecated in the contributing document
