### ISSUE TITLE
Add glossary of terms to documentation

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#175]
We should consider adding a [glossary of terms](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary) to the documentation.

As an example of what this could look like, we can look at [Sphinx](https://www.sphinx-doc.org/en/master/glossary.html) and [NannyML](https://nannyml.readthedocs.io/en/stable/glossary.html).

**Comment by mdbenito** [comment]
Good idea. We might want to use a different style too

**Comment by mdbenito** [comment]
Related: With the switch to mkdocs we added abbreviations to `docs_includes/abbreviations.md`.
