### ISSUE TITLE
Documentation should only be published after a release

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#179]
It seems like GH pages are rebuilt from develop. This would be ok if one could switch versions like in readthedocs, but as it is, the docs document features not in the pypi package.

Either we offer both the stable and the development version or we limit the public pages to the released version

**Comment by mdbenito** [comment]
@AnesBenmerzoug maybe it's better to switch to read the docs and have multiple versions online?

**Comment by AnesBenmerzoug** [comment]
@mdbenito I agree. A switch to readthedocs seems like it would make our lives easier.

Do we already have an account for that?

**Comment by mdbenito** [comment]
Not that I know of. I thought kyle might use RTD but I couldn't even find any built docs for it (no links to docs and.. OMG NO BADGES!! 😱).

So I guess we can create an account. We might want to pay for private docs too, we'll discuss on Monday.

**Comment by mdbenito** [comment]
In case someone wants to work on this, I made some tweaks for RTD (untested) in https://github.com/appliedAI-Initiative/pyDVL/tree/feature/rtd

**Comment by mdbenito** [comment]
Instead of read the docs, we can just publish to subfolders inside `gh-pages` and use a custom dropdown to select among them. At the root we leave the latest stable release.
