### ISSUE TITLE
Create abstraction for `Cache`

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#189]
We should create a proper abstraction of the caching to make the code base cleaner and to allow alternative implementations.

We currently only support  `Memcached`.

This is related to issue #124

**Comment by mdbenito** [comment]
Additionally, the lifecyle of the cached objects is difficult to understand. Because we pass cache configs and the memoization decorator connects and holds the client, it is awkward to flush the cache.

**Comment by AnesBenmerzoug** [comment]
Consider writing a notebook about caching.

**Comment by mdbenito** [comment]
This should work

```python
u1 = Utility(model, data, scorer)
u2 = Utility(model2, data, scorer)

v1 = compute_values(u1)  # misses cache
v2 = compute_values(u2)  # misses cache
v3 = compute_values(u1)  # hits cache
```
