### ISSUE TITLE
Implement stratified sampling

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#223]
* [ ] Implement the optimal strategy described in [1].
* [x] #226
* [ ] Reproduce their results (possibly, but not necessarily including the stratified sampling strategy of [2]), in particular all information in Tables 1-5

**[1]** Castro, Javier, Daniel Gómez, Elisenda Molina, and Juan Tejada. “Improving Polynomial Estimation of the Shapley Value by Stratified Random Sampling with Optimum Allocation.” Computers & Operations Research 82 (June 1, 2017): 180–88. https://doi.org/10.1016/j.cor.2017.01.019.
**[2]** Maleki, Sasan, Long Tran-Thanh, Greg Hines, Talal Rahwan, and Alex Rogers. “Bounding the Estimation Error of Sampling-Based Shapley Value Approximation.” ArXiv:1306.4265 [Cs], February 12, 2014. http://arxiv.org/abs/1306.4265.

**Comment by schroedk** [comment]
Stratified sampling is implemented in #558. Reproduction is excluded from this issue for now. Please reopen a separate issue.
