### ISSUE TITLE
Add doc with common Data Valuation benchmarks / tasks

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#244]
Just short descriptions and links to the functions implementing / helping with them

* Data removal / addition
* Outlier detection
* Data debugging
* etc.

**Comment by mdbenito** [comment]
I have written a long-ish blog post about this and added just a few keywords to the documentation in #404. Instead of copying it we should just link to it once we release a stable version and publish the post.

**Comment by AnesBenmerzoug** [comment]
If I'm not mistaken, this was taken care of in #492
