### ISSUE TITLE
Mismatch between README in develop and released version

### ISSUE THREAD

**Issue by mojtaba732** [aai-institute/pyDVL#246]
When we run the example of [readme](https://github.com/appliedAI-Initiative/pyDVL) page, an error occurs in

values = compute_shapley_values(
    u=utility, n_iterations=100, mode="truncated_montecarlo"
)

the error is 
TypeError: truncated_montecarlo_shapley() got an unexpected keyword argument 'n_iterations'

**Comment by mdbenito** [comment]
Hi, in v0.3.0 it is `max_iterations`. For 0.4.0 we renamed the parameter but haven't released yet. The readme you are reading is in the develop branch, so you see the new documentation.

**Comment by mdbenito** [comment]
Also see #179

**Comment by mdbenito** [comment]
@mojtaba732 I just released 0.4.0. Upgrade with pip and you should be good to go. [Release notes here](https://github.com/appliedAI-Initiative/pyDVL/releases/tag/v0.4.0)

**Comment by mojtaba732** [comment]
@mdbenito Thanks
