### ISSUE TITLE
Paper repro: IF in DL are fragile

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#260]
Reproduce all experiments in _[Influence Functions in Deep Learning Are Fragile](https://openreview.net/forum?id=xHKVVHGDOEk). Samyadeep Basu, Phil Pope, Soheil Feizi. ICLR 2021_

**Comment by AnesBenmerzoug** [comment]
Is this issue still relevant?

**Comment by mdbenito** [comment]
It's been superseded by more extensive experiments, so I guess not.
