### ISSUE TITLE
Simplify progress bars

### ISSUE THREAD

**Issue by mdbenito** [aai-institute/pyDVL#269]
- [ ] Throw away `maybe_progress` and the silly mock: tqdm supports `display=False` 🤦🏽 
- [ ] Find something (anything!) better than:
```python
    repeat_indices = takewhile(lambda _: not done(result), cycle(indices))
    pbar = tqdm(disable=not progress, position=job_id, total=100, unit="%")
    for idx in repeat_indices:
        pbar.n = 100 * done.completion()
        pbar.refresh()
```
- [x] Test / solve for parallel execution

**Comment by Aditya7024** [comment]
Hey @mdbenito  can you please specify about the source code folder/file so that I can get more information about the issue.

**Comment by mdbenito** [comment]
Hi @Aditya7024 , sorry for the late reply. I totally missed the notification for your comment. We use a wrapper around tqdm called `maybe_progress` that simply mimics what tqdm's option `display=False` does. The issue is about removing this wrapper altogether and calling tqdm directly. There are a couple of places where this already happens, just grep the code.

The second item is about a nicer way of using percentages of completion based on the value given by `done.completion()` (the stopping criterion). And it's a bit trickier. If you are still looking for something to do, then I would simply start with the first bullet point. 🙏🏽
