### ISSUE TITLE
Parallelise influence calculation

### ISSUE THREAD

**Issue by Xuzzo** [aai-institute/pyDVL#277]
There are a few loops in the influence code that may use the speed up from parallelisation:
- in TorchDifferentiable.split_grad and TorchDifferentiable.mvp
- in _calculate_influences_pert, within general.py
- in conjugate_gradient, within inversion_methods
Since they all do backpropagation under the hood, memory and not compute may be the biggest bottleneck in practice. Regardless, including the possibility to parallelise should be quite straightforward. 

Related to #26

**Comment by mdbenito** [comment]
If we want to run experiments on larger datasets this is a must => Bumping the priority
