### ISSUE TITLE
Better handling of optional dependencies

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#313]

**Comment by AnesBenmerzoug** [comment]
#218 is related to this.

**Comment by mdbenito** [comment]
See https://hanxiao.io/2019/11/07/A-Better-Practice-for-Managing-extras-require-Dependencies-in-Python/ for a flexible approach

**Comment by AnesBenmerzoug** [comment]
Here's a different solution using `pyproject.toml`: https://hynek.me/articles/python-recursive-optional-dependencies/

I think we should consider consider eventually moving to that instead of `setup.py`.

**Comment by schroedk** [comment]
This is not an issue at the moment, consider reopening if extras are getting more complicated.
