### ISSUE TITLE
Improve training process in influence notebooks

### ISSUE THREAD

**Issue by Xuzzo** [aai-institute/pyDVL#351]
In the notebooks, all the torch models are trained in a sloppy way, e.g. without a proper stopping criterion apart for number of steps. This was to show that influences can be robust even with non perfectly convex models. Nevertheless, we could be more elegant with handling training parameters and processes.

**Comment by schroedk** [comment]
Will close this, training is not elegant but okay. If there is still an issue, please reopen.
