### ISSUE TITLE
Utility indices are the same for training and test sets?

### ISSUE THREAD

**Issue by patrickmesana** [aai-institute/pyDVL#379]
In the Utility class, _utility method:

`x_train, y_train = self.data.get_training_data(list(indices)) `
`x_test, y_test = self.data.get_test_data(list(indices))`

Is it correct? For leave-one-out for example, you would query the same indices both for train and test, meaning that the indices length is way bigger than the test set size for a traditional train/test split

**Comment by AnesBenmerzoug** [comment]
In the default implementation of the [`get_test_data`](https://github.com/appliedAI-Initiative/pyDVL/blob/839a22c83a36b6e19fd0a5c7f3eb68472662accf/src/pydvl/utils/dataset.py#L164) method, the indices are ignored and the test data is returned as is.

As written in the method's docstring, this was done on purpose to keep the same interface as `get_training_data` and to allow other possible uses.

**Comment by patrickmesana** [comment]
Thanks for the answer
