### ISSUE TITLE
ImportError: cannot import name 'TorchTwiceDifferentiable' from 'pydvl.influence' 

### ISSUE THREAD

**Issue by om-hb** [aai-institute/pyDVL#435]
Hi,

I tried to run some of the example notebooks as well as the short usage example for Influence Functions from your README using V0.7.0. All of them fail with the following error:
`ImportError: cannot import name 'TorchTwiceDifferentiable' from 'pydvl.influence'` triggered by the import `from pydvl.influence import TorchTwiceDifferentiable`.

Looking at the code, `TorchTwiceDifferentiable` was moved to `src/pydvl/influence/torch/torch_differentiable.py`. I guess either the import in the examples needs to be changed to `from pydvl.influence.torch import TorchTwiceDifferentiable` or the __init__.py of the influence package needs to be adjusted?

Let me know if you need any additional information!

Thank you!

**Comment by mdbenito** [comment]
Thanks for the report @om-hb . Indeed the imports are wrong and we need to fix them. @schroedk is on it 🙏🏽
