### ISSUE TITLE
Add `sample_weights` option to utility.

### ISSUE THREAD

**Issue by kosmitive** [aai-institute/pyDVL#448]
While it is clear for models which have a `class_weights` parameter in the constructor, some models only support setting `sample_weights` in `fit`. We have two options 

1. Add mechanism to utility to pass parameters to the `fit` method.
2. Wrap the model, e.g. proxy all methods and when `fit` is called, add `sample_weights`

to accept imbalanced datasets. Which method would you prefer?

I would tend for 2., because the interface `fit` is more compact and reusable.

**Comment by mdbenito** [comment]
I would say that balancing class imbalance is the responsibility of the user, and therefore so is wrapping the model to do whatever makes sense for it. I don't think pydvl needs to provide any kind of support for this. I would agree to using imbalanced data in an example to illustrate the problem, thouh. Or do you think there is some non-trivial situation that we should handle?
