### ISSUE TITLE
NameError: name 'PickleSerde' is not defined

### ISSUE THREAD

**Issue by seyedamirshobeiri** [aai-institute/pyDVL#505]
---------------------------------------------------------------------------

NameError                                 Traceback (most recent call last)

[<ipython-input-5-cd1b1f042415>](https://localhost:8080/#) in <cell line: 5>()
      3 from torch.utils.data import DataLoader, TensorDataset
      4 
----> 5 from pydvl.influence.torch import DirectInfluence
      6 from pydvl.influence.torch.util import NestedTorchCatAggregator, TorchNumpyConverter
      7 from pydvl.influence import SequentialInfluenceCalculator

5 frames

[/usr/local/lib/python3.10/dist-packages/pydvl/utils/caching/memcached.py](https://localhost:8080/#) in MemcachedClientConfig()
     45     timeout: float = 1.0
     46     no_delay: bool = True
---> 47     serde: PickleSerde = PickleSerde(pickle_version=PICKLE_VERSION)
     48 
     49 

NameError: name 'PickleSerde' is not defined

**Comment by schroedk** [comment]
Hi @seyedamirshobeiri, thanks for reporting. Could you please provide a minimal working example of what you are trying to do, which produces the error?

My first wild guess would be, that you need to install pydvl with "memcached" extra
`pip install pydvl[memcached]`

Are you trying to create a `MemcachedClientConfig` object?

**Comment by seyedamirshobeiri** [comment]
Thank you.it's work now.Thank you So much for your assistance.

**Comment by schroedk** [comment]
We should extend the documentation regarding `memcached`. Also there is an import  try/except in the memcached module, which should be either revised or a logging message should be added.

**Comment by mdbenito** [comment]
We can move the check to the __init__ and only expose the symbols if memcached is available.
