### ISSUE TITLE
Move tolerate fixture to separate repository

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#539]
With the changes in #529, we no longer use the tolerate fixture and we should therefore remove it from the repository. However I think it is useful and there may be other uses for it beyond pyDVL. Therefore I suggest we move it a separate repository and open-source it.

All the related code can be found in [tests/tolerate.py](https://github.com/aai-institute/pyDVL/blob/develop/tests/tolerate.py) and [tests/conftest.py](https://github.com/aai-institute/pyDVL/blob/develop/tests/conftest.py).

We should refer to [pytest's documentation](https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html#writing-your-own-plugin) for instructions on how to create a plugin.

It turns out that there is a similar plugin called [pytest-repeat](https://github.com/pytest-dev/pytest-repeat) that allows repeating tests on failure. However our implementation allows setting the number of repetitions inside a test's function. We could contribute that change to that other plugin but that would take longer and would involve a lot more communication overhead.

**Comment by AnesBenmerzoug** [comment]
After a bit of search I found that there already exists a pytest plugin call [pytest-rerunfailures](https://github.com/pytest-dev/pytest-rerunfailures) that reruns tests on failure. We should perhaps removing our code and use that instead.

**Comment by mdbenito** [comment]
Rerunfailures is pretty neat. As soon as we move to 3.8 we should integrate
it for the stochastic tests
