### ISSUE TITLE
Fix rendering of influences plot in readme

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#540]
With the recent change in #532 that moved all png images to git lfs, the influences plot in the readme no longer renders properly.

![image](https://github.com/aai-institute/pyDVL/assets/27914730/f09c14e1-ebd9-4487-9e24-8292c71f4ea4)

**EDIT** This could be related to the recent change we made to use absolute urls in the readme.

**Comment by mdbenito** [comment]
Perhaps related, the images do not show up in [the example gallery](https://pydvl.org/devel/examples/)

**Comment by AnesBenmerzoug** [comment]
For the example gallery, this could related to not setting `lfs: true` in CI for the [checkout action](https://github.com/actions/checkout).

**Comment by mdbenito** [comment]
> For the example gallery, this could related to not setting `lfs: true` in CI for the [checkout action](https://github.com/actions/checkout).

Yes, I've added it
