### ISSUE TITLE
OSError: no library called "cairo-2" was found

### ISSUE THREAD

**Issue by schroedk** [aai-institute/pyDVL#544]
When trying to build the documentation via

`mkdocs build`

or

`mkdocs serve`

I observed the error

`OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found`

Setup:
- Python 3.8.19
- Mac OS 14.4 / M2 Max

The error is due to the corresponding lib files not linked to locations, where mkdocs is looking for it, when `cairo` is installed via
brew.

Also observed here:
- https://github.com/squidfunk/mkdocs-material/issues/5121
- https://github.com/dora-metrics/pelorus/issues/1073
- https://github.com/squidfunk/mkdocs-material/issues/6071

The described workaround is setting the fallback environment variable:

`export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/opt/homebrew/lib`

I suggest to mention this in our `CONTRIBUTING.md`.

**Comment by schroedk** [comment]
@mdbenito @AnesBenmerzoug did you have to install the non-python dependencies manually? So something like:

`apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev`

**Comment by AnesBenmerzoug** [comment]
I am not 100% sure, but I would say yes.
