### ISSUE TITLE
Document Parallel Backends' internals

### ISSUE THREAD

**Issue by AnesBenmerzoug** [aai-institute/pyDVL#555]
In order to better understand how the different parallel backends work and how one would implement a new, we need to document their internals. For example, we need to be able to answer the question: Do I need to `put()` values before calling a parallel function? do I need to `get()` my arguments in the method that is sent to the workers? why not?

**Comment by mdbenito** [comment]
Partially addressed [here](https://github.com/aai-institute/pyDVL/pull/549/files/e23256ba2166fbb6cfd58eb1f15663702b0e1b0a#r1553250280)

**Comment by mdbenito** [comment]
With the transition to 100% joblib this issue is obsolete
