### ISSUE TITLE
Removal of `np.float_`

### ISSUE THREAD

**Issue by schroedk** [aai-institute/pyDVL#603]
In the latest test runs, we observe the error

```AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.```

This is due to the installation of NumPy 2.0 in the test environment. Until now, we have now upper bound on the NumPy version in the requirements.

Check, if it makes sense to add an upper bound or replace the usage of `np.float_`.

**Comment by janosg** [comment]
There is a ruff rule that can do most of the numpy 2.0 related changes automatically: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#ruff-plugin

I think we want to wait with the full adoption of ruff (as planned in #548) until the refactoring is done but you could run ruff with only rule "NPY201" enabled.

**Comment by schroedk** [comment]
@janosg thanks for the suggestion, very helpful. This revealed the change from
`np.alltrue` to `np.all`, which I will integrate into the PR.
